<a href="https://colab.research.google.com/github/HaniAmiraaDa/PPBMyDessertDaftarMenuMakanan/blob/master/preprocessing_Repo1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
Dataset = pd.read_csv("/content/drive/MyDrive/heart_attack_prediction_dataset.csv")

# importing an array of features
x = Dataset.iloc[:, :-1].values
# importing an array of dependent variable
y = Dataset.iloc[:, -1].values

In [ ]:
print(x) # returns an array of features

[['BMW7812' 67 'Male' ... 'Argentina' 'South America'
  'Southern Hemisphere']
 ['CZE1114' 21 'Male' ... 'Canada' 'North America' 'Northern Hemisphere']
 ['BNI9906' 21 'Female' ... 'France' 'Europe' 'Northern Hemisphere']
 ...
 ['XKA5925' 47 'Male' ... 'Brazil' 'South America' 'Southern Hemisphere']
 ['EPE6801' 36 'Male' ... 'Brazil' 'South America' 'Southern Hemisphere']
 ['ZWN9666' 25 'Female' ... 'United Kingdom' 'Europe'
  'Northern Hemisphere']]


In [ ]:
print(y) # viewing an array of the dependent variable.

[0 0 0 ... 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2,random_state= 1)

In [ ]:
print(x_train)

[['HRM3348' 54 'Male' ... 'Argentina' 'South America'
  'Southern Hemisphere']
 ['YOD3294' 31 'Male' ... 'United States' 'North America'
  'Northern Hemisphere']
 ['KNJ1597' 27 'Male' ... 'Canada' 'North America' 'Northern Hemisphere']
 ...
 ['BKP7949' 79 'Male' ... 'United States' 'North America'
  'Northern Hemisphere']
 ['VZZ5398' 50 'Male' ... 'Italy' 'Europe' 'Southern Hemisphere']
 ['KZY7247' 75 'Female' ... 'Brazil' 'South America'
  'Southern Hemisphere']]


In [ ]:
print(x_test)

[['ZMM8868' 57 'Male' ... 'Thailand' 'Asia' 'Northern Hemisphere']
 ['GAV2034' 19 'Female' ... 'Spain' 'Europe' 'Southern Hemisphere']
 ['JLR6973' 89 'Female' ... 'Canada' 'North America'
  'Northern Hemisphere']
 ...
 ['NIU0083' 86 'Male' ... 'Spain' 'Europe' 'Southern Hemisphere']
 ['PFA1167' 28 'Female' ... 'Argentina' 'South America'
  'Southern Hemisphere']
 ['RMS3012' 20 'Male' ... 'United Kingdom' 'Europe' 'Northern Hemisphere']]


In [ ]:
print(y_train)

[1 0 0 ... 0 1 0]


In [ ]:
print(y_test)

[1 0 0 ... 0 0 1]
